/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OfficeRouteImport } from "./routes/office";
import { Route as ThreadRouteImport } from "./routes/$threadId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OfficeRoute = OfficeRouteImport.update({
  id: "/office",
  path: "/office",
  getParentRoute: () => rootRouteImport,
} as any);
const ThreadRoute = ThreadRouteImport.update({
  id: "/$threadId",
  path: "/$threadId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/office": typeof OfficeRoute;
  "/$threadId": typeof ThreadRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/office": typeof OfficeRoute;
  "/$threadId": typeof ThreadRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/office": typeof OfficeRoute;
  "/$threadId": typeof ThreadRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/office" | "/$threadId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/office" | "/$threadId";
  id: "__root__" | "/" | "/office" | "/$threadId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OfficeRoute: typeof OfficeRoute;
  ThreadRoute: typeof ThreadRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/office": {
      id: "/office";
      path: "/office";
      fullPath: "/office";
      preLoaderRoute: typeof OfficeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$threadId": {
      id: "/$threadId";
      path: "/$threadId";
      fullPath: "/$threadId";
      preLoaderRoute: typeof ThreadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  OfficeRoute,
  ThreadRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
